# Use root/mysql as user/password credentials

version: '3.8'

services:

    db:
        image: mysql
        command:
            --default-authentication-plugin=admin
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: admin
        ports:
            - "33306:3306"